### ISSUE TITLE
Support for additional users

### ISSUE THREAD

**Issue by siliconcupcake** [agstrike/silverstrike#119]
There seems to be an option to signup, but it's disabled. Is there any particular reason behind that decision ?
I would like to create multiple profiles for each family member. Any help regarding how I can achieve that is much appreciated. Thanks in advance.

**Comment by simhnna** [comment]
You should be able to create multiple users using the django admin.
Signup is disabled, because currently all users of an instance share all data. So if you enable signup anyone can access the stored data. If you want to share data between your family you can do that now. Seperating data based on users is on my todo list, but not very high up, since it won't be of any use to me personally
