### ISSUE TITLE
No user data separation, everyone views everyones data

### ISSUE THREAD

**Issue by boscoMW** [agstrike/silverstrike#99]
According to the documentation
> Firefly does support multiple users, but each user gets their own data.

This is not the case because currently any user can see all the other users data, data such as accounts, transactions are not associated to the user and no filtering based on user id is done when querying thus any user is able to see all the accounts and transactions.

**Comment by simhnna** [comment]
Yeah, that's firefly. Silverstrike currently doesn't support users with different accounts. I'm planning on supporting that in the future, but currently my focus is on covering my needs. And since this is intended for personal self hosting in the first place, I figured it's not that important to support seperated accounts.
